title: Hrishi's Blog
description: "Hi there 👋 I’m Hrishi. I’m a software developer interested in building useful things for people. I started this blog to write about software development (mostly), but I also write about other things from time to time - like movies I’m watching, or the books I’m reading and other things I enjoy."
url: "https://www.hrishi.io"
author:
  name: Hrishikesh S
  url: https://www.hrishi.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
